#!/usr/bin/env python3
"""Build a self-contained-data Mark III interactive review surface."""
from __future__ import annotations
import argparse,base64,json
from pathlib import Path

def build_html(glb,manifest,parameters,verification,serviceability,roundtrip):
    data={'manifest':json.loads(manifest.read_text()),'parameters':json.loads(parameters.read_text()),'verification':json.loads(verification.read_text()),'serviceability':json.loads(serviceability.read_text()),'roundtrip':json.loads(roundtrip.read_text())}
    glb64=base64.b64encode(glb.read_bytes()).decode('ascii');payload=json.dumps(data,separators=(',',':')).replace('</','<\\/')
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mark III v0.2 Interactive Review</title>
<style>*{{box-sizing:border-box}}body{{margin:0;background:#0a0e13;color:#dce4ec;font:13px system-ui,Segoe UI,sans-serif;overflow:hidden}}#app{{display:grid;grid-template-columns:320px 1fr 340px;grid-template-rows:54px calc(100vh - 82px) 28px;height:100vh}}header{{grid-column:1/4;display:flex;align-items:center;gap:16px;padding:0 18px;background:#101720;border-bottom:1px solid #283544}}header b{{font-size:17px}}.tag{{padding:5px 9px;border:1px solid #385069;border-radius:12px;color:#9fc0dc}}aside{{background:#0f151d;overflow:auto;padding:12px;border-right:1px solid #263342}}#right{{border-left:1px solid #263342;border-right:0}}#viewport{{position:relative;min-width:0}}canvas{{display:block}}h3{{font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:#8ca8bf;margin:14px 0 8px}}button,select,input{{background:#17222d;color:#dce4ec;border:1px solid #34475a;border-radius:5px;padding:7px}}button{{cursor:pointer}}.row{{display:flex;gap:6px;flex-wrap:wrap}}.layer{{display:grid;grid-template-columns:22px 1fr auto;gap:5px;align-items:center;padding:4px 0}}.count,.muted{{color:#8194a5}}#search{{width:100%}}.result{{padding:7px;border-bottom:1px solid #1e2a36;cursor:pointer;overflow-wrap:anywhere}}.result:hover,.result.active{{background:#1b2937}}.metric{{display:grid;grid-template-columns:1fr 1.25fr;gap:6px 8px}}.metric b{{overflow-wrap:anywhere}}.good{{color:#7fd1a1}}.warn{{color:#e4c278}}.bad{{color:#e38a8a}}.gap{{padding:7px 0;border-bottom:1px solid #24313e}}label.ctrl{{display:grid;gap:5px;margin:8px 0}}input[type=range]{{width:100%;padding:0}}footer{{grid-column:1/4;padding:5px 12px;color:#7f91a1;background:#101720;border-top:1px solid #263342}}#loading{{position:absolute;inset:0;display:grid;place-items:center;background:#0a0e13;color:#9fc0dc;z-index:4}}#selection{{position:absolute;left:12px;bottom:12px;background:#101720dd;border:1px solid #33485c;padding:8px;max-width:70%;border-radius:5px}}.small{{font-size:11px;color:#91a4b5;line-height:1.4}}</style></head>
<body><div id="app"><header><b>Mark III v0.2 — Serviceable Modular Reference</b><span class="tag">339 named nodes</span><span class="tag">Reference only · not validated hardware</span><span class="tag">Issue #32</span></header>
<aside><h3>View</h3><div class="row"><button id="home">Home</button><button id="front">Front</button><button id="side">Side</button><button id="top">Top</button></div>
<label class="ctrl">Explode <span id="explodeValue">0%</span><input id="explode" type="range" min="0" max="100" value="0"></label>
<label class="ctrl">Cutaway axis<select id="cutaway"><option value="none">None</option><option value="x">X</option><option value="y">Y</option><option value="z">Z</option></select></label>
<label class="ctrl">Cut position <span id="cutValue">0.0 m</span><input id="cutPosition" type="range" min="-1" max="1" step="0.01" value="0"></label>
<label class="ctrl">Array review<select id="arraySelect"><option value="all">All guides</option><option value="none">Hide guides</option><option value="1">1 module</option><option value="2">2 modules</option><option value="4">4 modules</option><option value="8">8 modules</option><option value="18">18 modules</option></select></label>
<label><input id="wireframe" type="checkbox"> Wireframe</label><label><input id="envelopes" type="checkbox" checked> Transparent envelopes</label>
<h3>Layers</h3><div id="layers"></div><h3>Search</h3><input id="search" placeholder="component, family, evidence, gate"><div id="results"></div></aside>
<div id="viewport"><div id="loading">Loading embedded GLB…</div><div id="selection">Select a component to inspect.</div></div>
<aside id="right"><h3>Qualification</h3><div id="status"></div><h3>Selected component</h3><div id="detail" class="muted">No selection.</div><h3>Source conflicts</h3><div id="conflicts"></div><h3>Known unknowns</h3><div id="gaps"></div></aside>
<footer id="footer"></footer></div><script id="reviewData" type="application/json">{payload}</script>
<script type="module">import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';import{{OrbitControls}}from'https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js';import{{GLTFLoader}}from'https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/loaders/GLTFLoader.js';
const D=JSON.parse(document.getElementById('reviewData').textContent),C=D.manifest.components,R=new Map(C.map(x=>[x.node_name,x]));
const group=x=>{{if(x.family==='array_guide')return'Array guides';if(['service_clearance','removal_path','connector_access','cable_bend_space'].includes(x.family))return'Service / access envelopes';if(['shell_panel','solar_hull_skin','fastener'].includes(x.family))return'Exterior / Solar Hull';if(['coupler','coupler_latch','coupler_bridge'].includes(x.family))return'Coupling';if(['solenoid','resonator','field_guide'].includes(x.family))return'RFS / EMFF modules';if(['energy','controller'].includes(x.family))return'Energy / controls';if(['sensor','comms'].includes(x.family))return'Sensors / comms';if(['cable_tray','harness'].includes(x.family))return'Cable / harness';if(x.subsystem==='arm_system')return'Arms / joints';if(['process_tunnel','sample_cartridge'].includes(x.family))return'Process chamber';return'Structure / isolation'}};
const groups=[...new Set(C.map(group))].sort(),enabled=new Map(groups.map(g=>[g,true]));const viewport=document.getElementById('viewport');const scene=new THREE.Scene();scene.background=new THREE.Color(0x0a0e13);const cam=new THREE.PerspectiveCamera(42,1,.001,100);cam.position.set(1.7,-1.8,1.35);const renderer=new THREE.WebGLRenderer({{antialias:true}});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;viewport.prepend(renderer.domElement);const controls=new OrbitControls(cam,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);scene.add(new THREE.HemisphereLight(0xe4efff,0x26313e,2));const key=new THREE.DirectionalLight(0xffffff,2.1);key.position.set(2,-2,3);scene.add(key);const grid=new THREE.GridHelper(5,50,0x294052,0x182633);grid.rotation.x=Math.PI/2;grid.position.z=-.35;scene.add(grid);
function resize(){{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);cam.aspect=w/h;cam.updateProjectionMatrix()}}addEventListener('resize',resize);resize();function view(p,t=[0,0,0]){{cam.position.set(...p);controls.target.set(...t);controls.update()}}home.onclick=()=>view([1.7,-1.8,1.35]);front.onclick=()=>view([-1.8,0,0]);side.onclick=()=>view([0,-1.8,0]);top.onclick=()=>view([0,0,1.8]);
let root=null;const bytes=Uint8Array.from(atob('{glb64}'),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{{type:'model/gltf-binary'}}));new GLTFLoader().load(url,g=>{{root=g.scene;scene.add(root);root.traverse(o=>{{if(o.isMesh){{o.userData.base=o.position.clone();o.userData.record=R.get(o.name)||null;o.material=o.material.clone()}}}});apply();loading.remove();URL.revokeObjectURL(url);populate('')}},undefined,e=>loading.textContent='GLB load failed: '+e.message);
const layers=document.getElementById('layers');for(const g of groups){{const l=document.createElement('label');l.className='layer';l.innerHTML=`<input type=checkbox checked><span>${{g}}</span><span class=count>${{C.filter(x=>group(x)===g).length}}</span>`;l.querySelector('input').onchange=e=>{{enabled.set(g,e.target.checked);apply()}};layers.appendChild(l)}}
function apply(){{if(!root)return;const arr=arraySelect.value;root.traverse(o=>{{if(!o.isMesh)return;const r=o.userData.record;if(!r)return;let v=enabled.get(group(r));if(r.family==='array_guide')v=v&&(arr==='all'||r.array_configuration===arr);o.visible=v;const env=['service_clearance','removal_path','connector_access','cable_bend_space','array_guide','field_guide'].includes(r.family);o.material.transparent=env&&envelopes.checked;o.material.opacity=env&&envelopes.checked?.13:1;o.material.depthWrite=!(env&&envelopes.checked)}})}}arraySelect.onchange=apply;envelopes.onchange=apply;wireframe.onchange=e=>root&&root.traverse(o=>{{if(o.isMesh)o.material.wireframe=e.target.checked}});
explode.oninput=e=>{{explodeValue.textContent=e.target.value+'%';const f=+e.target.value/100;if(root)root.traverse(o=>{{if(o.isMesh&&o.userData.record){{const c=o.userData.record.centroid_m,v=new THREE.Vector3(...c);if(v.length())v.normalize().multiplyScalar(f*.25);o.position.copy(o.userData.base).add(v)}}}})}};const plane=new THREE.Plane(new THREE.Vector3(),0);function clip(){{const mode=cutaway.value,p=+cutPosition.value;cutValue.textContent=p.toFixed(2)+' m';plane.normal.set(mode==='x'?-1:0,mode==='y'?-1:0,mode==='z'?-1:0);plane.constant=p;if(root)root.traverse(o=>{{if(o.isMesh)o.material.clippingPlanes=mode==='none'?[]:[plane]}})}}cutaway.onchange=clip;cutPosition.oninput=clip;
function details(r){{return `<div class=metric><span>Name</span><b>${{r.node_name}}</b><span>Family</span><b>${{r.family}}</b><span>Subsystem</span><b>${{r.subsystem}}</b><span>Evidence</span><b>${{r.evidence_state}}</b><span>Physical</span><b>${{r.physical}}</b><span>Maintainable</span><b>${{r.maintainable}}</b><span>Attachment</span><b>${{r.attachment_parent||'—'}}</b><span>Cable route</span><b>${{r.cable_route||'—'}}</b><span>Panel access</span><b>${{r.panel_access||'—'}}</b><span>Clearance</span><b>${{r.service_clearance||'—'}}</b><span>Removal</span><b>${{r.removal_path||'—'}}</b><span>Extents</span><b>${{r.extents_m.map(v=>v.toFixed(3)).join(' × ')}} m</b></div><p class=small><b>Review gate:</b> ${{r.review_gate}}</p><p class=small><b>Source basis:</b> ${{r.source_basis}}</p>`}}function choose(r){{detail.innerHTML=details(r);selection.textContent=r.node_name+' — '+r.evidence_state;document.querySelectorAll('.result').forEach(x=>x.classList.toggle('active',x.dataset.n===r.node_name))}}
const ray=new THREE.Raycaster(),ptr=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',e=>{{if(!root)return;const b=renderer.domElement.getBoundingClientRect();ptr.x=(e.clientX-b.left)/b.width*2-1;ptr.y=-(e.clientY-b.top)/b.height*2+1;ray.setFromCamera(ptr,cam);const h=ray.intersectObjects(root.children,true).find(x=>x.object.userData.record);if(h)choose(h.object.userData.record)}});function populate(q){{q=q.trim().toLowerCase();results.innerHTML='';for(const r of C.filter(r=>!q||[r.node_name,r.family,r.subsystem,r.evidence_state,r.review_gate,r.source_basis].join(' ').toLowerCase().includes(q)).slice(0,300)){{const d=document.createElement('div');d.className='result';d.dataset.n=r.node_name;d.innerHTML=`<b>${{r.node_name}}</b><div class=small>${{r.family}} · ${{r.evidence_state}}</div>`;d.onclick=()=>choose(r);results.appendChild(d)}}}}search.oninput=e=>populate(e.target.value);
const s=D.serviceability,v=D.verification,rt=D.roundtrip;status.innerHTML=`<div class=metric><span>Geometry</span><b class=good>${{v.status}}</b><span>Serviceability</span><b class=good>${{s.status}}</b><span>GLB round-trip</span><b class=good>${{rt.status}}</b><span>Named nodes</span><b>${{C.length}}</b><span>Physical nodes</span><b>${{s.counts.physical_nodes}}</b><span>Maintainable nodes</span><b>${{s.counts.maintainable_nodes}}</b><span>Clearance envelopes</span><b>${{s.counts.service_clearances}}</b><span>Removal paths</span><b>${{s.counts.removal_paths}}</b><span>Module envelope</span><b>${{s.canonical_module_envelope_m.extents.map(x=>x.toFixed(3)).join(' × ')}} m</b></div>`;conflicts.innerHTML=D.parameters.source_conflicts.map(x=>`<div class=gap><b>${{x.id}}</b> — ${{x.description}}<div class=small>${{x.resolution}}</div></div>`).join('');gaps.innerHTML=D.parameters.known_unknowns.map(x=>`<div class=gap><b>${{x.id}}</b> — ${{x.description}}</div>`).join('');footer.textContent=`${{C.length}} selectable nodes · Mark III issue #32 · stacked above Luke PR #30 · array guides illustrative only`;(function animate(){{requestAnimationFrame(animate);controls.update();renderer.render(scene,cam)}})();</script></body></html>'''

def main():
    ap=argparse.ArgumentParser();
    for k in ('glb','manifest','parameters','verification','serviceability','roundtrip','output'):ap.add_argument('--'+k,type=Path,required=True)
    a=ap.parse_args();html=build_html(a.glb,a.manifest,a.parameters,a.verification,a.serviceability,a.roundtrip);a.output.write_text(html,encoding='utf-8');print(json.dumps({'status':'PASS_INTERACTIVE_REVIEW_SURFACE','path':a.output.name,'bytes':a.output.stat().st_size,'component_nodes':json.loads(a.manifest.read_text())['node_count']},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
